import type { EvidenceRecord } from './evidence.js';

/**
 * THE RESEARCH REPORT CONTRACT — versioned internal representation of an imported research report.
 *
 * A report is UNTRUSTED INPUT. It arrives from an external research tool (Gemini Deep Research, an approved agent
 * environment, a human writing notes) and nothing in it is believed until it has been through extraction,
 * validation and human approval. The contract exists so that at every later point the system can answer:
 *
 *   "Where did this fact come from?"     -> sourceReportId + the evidence attached to the claim
 *   "Did the source actually support it?" -> the evidence level, which only a human can take to SUPPORTED
 *
 * Versioned because the shape will change as Phase 2 learns what a good report looks like, and old reports must
 * stay readable as the evidence for leads that were already approved from them.
 */

export const RESEARCH_REPORT_CONTRACT_VERSION = '1.0' as const;

export const RESEARCH_PROVIDERS = ['GEMINI_DEEP_RESEARCH', 'CLAUDE_CODE', 'ANTIGRAVITY', 'HUMAN', 'OTHER'] as const;
export type ResearchProvider = (typeof RESEARCH_PROVIDERS)[number];

/** Where a report is in the pipeline. Each stage is entered only when the previous one succeeded. */
export const REPORT_STAGES = ['RECEIVED', 'PARSED', 'EXTRACTED', 'NORMALIZED', 'DEDUPLICATED', 'EVIDENCE_CHECKED', 'QUALIFIED', 'AWAITING_REVIEW', 'REVIEWED', 'REJECTED'] as const;
export type ReportStage = (typeof REPORT_STAGES)[number];

export const REPORT_FORMATS = ['markdown', 'text', 'json', 'csv'] as const;
export type ReportFormat = (typeof REPORT_FORMATS)[number];

export interface ReportFileMetadata {
  /** As supplied by the uploader. NEVER used as a filesystem path. */
  originalFilename: string;
  byteSize: number;
  format: ReportFormat;
  /** Hash of the raw bytes, so the stored report can be proven to be what was uploaded. */
  sha256: string;
}

/**
 * A single factual assertion extracted from a report, with the evidence offered for it.
 *
 * `value` is what the report says; `evidence` is why anyone should believe it. They are separate on purpose: a
 * claim with no evidence is still recorded, so the reviewer can see what was asserted and reject it knowingly,
 * rather than the system silently dropping it.
 */
export interface ExtractedClaim {
  field: string;
  value: string | null;
  /** Confidence AS STATED BY THE EXTRACTOR. Never treated as evidence; see `evidence` for that. */
  statedConfidence: 'HIGH' | 'MEDIUM' | 'LOW' | 'UNKNOWN';
  evidence: EvidenceRecord[];
  /** Where in the report this came from, so a reviewer can go and look. */
  reportLocation: string | null;
}

export const EXTRACTION_STATUSES = ['NOT_STARTED', 'OK', 'PARTIAL', 'FAILED'] as const;
export type ExtractionStatus = (typeof EXTRACTION_STATUSES)[number];

export interface ReportProblem {
  severity: 'ERROR' | 'WARNING';
  code: string;
  message: string;
  /** Candidate index or report location the problem relates to, when known. */
  at: string | null;
}

export interface ResearchReport {
  contractVersion: typeof RESEARCH_REPORT_CONTRACT_VERSION;
  /** Stable id for this report. Every candidate and every claim traces back to it. */
  sourceReportId: string;
  ingestedAt: string;
  provider: ResearchProvider;
  /** The named human who ran the research and dropped the report in. Never 'SYSTEM'. */
  operator: string;
  /** The brief this report was produced from, when it was generated by the OS. */
  promptId: string | null;
  file: ReportFileMetadata;
  /** Reference to where the raw report is stored. The raw text is kept verbatim, never edited. */
  rawStorageRef: string;
  stage: ReportStage;
  extractionStatus: ExtractionStatus;
  /** Candidate ids extracted from this report. The candidates themselves live separately. */
  candidateIds: string[];
  problems: ReportProblem[];
}

export const MAX_REPORT_BYTES = 5 * 1024 * 1024;
export const MAX_CANDIDATES_PER_REPORT = 200;
/** Filenames are metadata only. This rejects anything that could be mistaken for a path. */
const SAFE_FILENAME = /^[A-Za-z0-9][A-Za-z0-9 ._-]{0,200}$/;

/**
 * Validates an uploaded report's metadata BEFORE anything is parsed.
 *
 * Treats the upload as hostile: the filename is checked for traversal and control characters, the size is capped,
 * and the declared format must be one the parser actually supports. Nothing here executes or interprets content.
 */
export function reportMetadataProblems(file: Partial<ReportFileMetadata>): ReportProblem[] {
  const problems: ReportProblem[] = [];
  const err = (code: string, message: string) => problems.push({ severity: 'ERROR' as const, code, message, at: null });

  const name = file.originalFilename ?? '';
  if (!name) err('FILENAME_MISSING', 'the upload has no filename');
  else if (name.includes('\0')) err('FILENAME_UNSAFE', 'the filename contains a NUL byte');
  else if (name.includes('/') || name.includes('\\')) err('FILENAME_UNSAFE', 'the filename contains a path separator; filenames are metadata, never paths');
  else if (name.includes('..')) err('FILENAME_UNSAFE', 'the filename contains "..", which is never accepted');
  else if (!SAFE_FILENAME.test(name)) err('FILENAME_UNSAFE', 'the filename contains characters that are not accepted');

  if (typeof file.byteSize !== 'number' || !Number.isFinite(file.byteSize) || file.byteSize <= 0) err('SIZE_INVALID', 'the upload has no usable size');
  else if (file.byteSize > MAX_REPORT_BYTES) err('SIZE_EXCEEDED', `the upload is ${file.byteSize} bytes; the limit is ${MAX_REPORT_BYTES}`);

  if (!file.format || !(REPORT_FORMATS as readonly string[]).includes(file.format)) {
    err('FORMAT_UNSUPPORTED', `format must be one of ${REPORT_FORMATS.join(', ')}; anything else is never parsed`);
  }
  if (!file.sha256 || !/^[0-9a-f]{64}$/.test(file.sha256)) err('HASH_MISSING', 'the upload must be hashed before it is stored, so it can be proven unaltered');

  return problems;
}

/** A report may move to the next stage only from the stage before it. No skipping, no going back except to REJECTED. */
export function canAdvance(from: ReportStage, to: ReportStage): { allowed: boolean; reason: string } {
  if (to === 'REJECTED') return { allowed: true, reason: 'a report can be rejected at any stage' };
  const i = REPORT_STAGES.indexOf(from);
  const j = REPORT_STAGES.indexOf(to);
  if (from === 'REJECTED') return { allowed: false, reason: 'a rejected report is terminal; import it again as a new report' };
  if (j !== i + 1) return { allowed: false, reason: `${from} advances only to ${REPORT_STAGES[i + 1] ?? 'nothing'}, not ${to}` };
  return { allowed: true, reason: `${from} -> ${to}` };
}
